version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_LOAD_BALANCER_DNS=localhost
    container_name: frontend_container
    ports:
      - "3000:3000"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mobylab-app
      - SPRING_DATASOURCE_USERNAME=mobylab-app
      - SPRING_DATASOURCE_PASSWORD=mobylab-app

    ports:
      - "8090:8090"
    networks:
      - app_network
    depends_on:
      - db
  db:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: db_container
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: mobylab-app
      POSTGRES_USER: mobylab-app
      POSTGRES_PASSWORD: mobylab-app
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    build:
      context: pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
