version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=localhost
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - app_network
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mobylab-app
      - SPRING_DATASOURCE_USERNAME=mobylab-app
      - SPRING_DATASOURCE_PASSWORD=mobylab-app
      - AUTHENTICATION_SERVER_URL=http://authentication:5000
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8090:8090"
      - "5005:5005"
    networks:
      - app_network
    depends_on:
      - postgres
  authentication:
    build:
      context: authentication
      dockerfile: Dockerfile
    container_name: authentication_container
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - SQLALCHEMY_DATABASE_URI=postgresql://mobylab-app:mobylab-app@postgres:5432/mobylab-app
      - SECRET_KEY=your_secret_key
      - POSTGRES_USER=mobylab-app
      - POSTGRES_PASSWORD=mobylab-app
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: db_container
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: mobylab-app
      POSTGRES_USER: mobylab-app
      POSTGRES_PASSWORD: mobylab-app
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    build:
      context: pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # PGADMIN_CONFIG_SERVER_MODE: "False"
      # PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app_network
    configs:
      - source: pgpass
        target: /pgpass
      - source: servers.json
        target: /pgadmin4/servers.json  
configs:
  pgpass:
    content: postgres:5432:*:mobylab-app:mobylab-app
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "My Local Postgres 16.1",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "mobylab-app",
        "Username": "mobylab-app",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
