version: '3.8'

services:
  # frontend:
  #   image: frontend:latest
  #   container_name: frontend_container
  #   ports:
  #     - "3000:3000"
  # backend:
  #   image: backend:latest
  #   container_name: backend_container
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydatabase
  #     SPRING_DATASOURCE_USERNAME: myuser
  #     SPRING_DATASOURCE_PASSWORD: mypassword
  #     SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
  #   ports:
  #     - "8090:8090"
  #   networks:
  #     - app_network
  #   depends_on:
  #     - db
  db:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: db_container
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: mobylab-app
      POSTGRES_USER: mobylab-app
      POSTGRES_PASSWORD: mobylab-app
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
