apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sonar-demo
build:
  artifacts:
    - image: frontend-image
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: backend-image
      context: backend
      docker:
        dockerfile: Dockerfile
manifests:
   rawYaml:
      - k8s-*
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend-service
    port: 8090
    localPort: 8090
