apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sonar-demo
build:
  artifacts:
    - image: frontend-image
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: backend-image
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: authentication-image
      context: authentication
      docker:
        dockerfile: Dockerfile
    - image: db-image
      context: database
      docker:
        dockerfile: Dockerfile
    - image: pgadmin-image
      context: pgadmin
      docker:
        dockerfile: Dockerfile
    - image: portainer-image
      context: portainer
      docker:
        dockerfile: Dockerfile
    - image: postgres-image
      context: postgres
      docker:
        dockerfile: Dockerfile
manifests:
   rawYaml:
      - k8s-*
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend-service
    port: 8090
    localPort: 8090
  - resourceType: service
    resourceName: backend-service
    port: 5005
    localPort: 5005
  - resourceType: service
    resourceName: authentication-service
    port: 5000
    localPort: 5000
  - resourceType: service
    resourceName: db-service
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: pgadmin-service
    port: 5050
    localPort: 5050
  - resourceType: service
    resourceName: portainer-service
    port: 9000
    localPort: 9000
  - resourceType: service
    resourceName: grafana-service
    port: 3100
    localPort: 3100
  - resourceType: service
    resourceName: prometheus-service
    port: 9090
    localPort: 9090